version: '3'
services:
  eureka-server:
    image: microservices-eureka-server
    build:
      context: ./eureka-server
    ports:
      - "8761:8761"

  user-service:
    image: microservices-user-service
    build:
      context: ./user-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
    environment:
    - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka


  order-service:
    image: microservices-order-service
    build:
      context: ./order-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
      - user-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka